# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(400, 200)
        self.gridLayoutWidget = QtWidgets.QWidget(Widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_basket = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_basket.sizePolicy().hasHeightForWidth())
        self.pushButton_basket.setSizePolicy(sizePolicy)
        self.pushButton_basket.setObjectName("pushButton_basket")
        self.gridLayout.addWidget(self.pushButton_basket, 0, 1, 1, 1)
        self.pushButton_buy = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_buy.sizePolicy().hasHeightForWidth())
        self.pushButton_buy.setSizePolicy(sizePolicy)
        self.pushButton_buy.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton_buy, 0, 0, 1, 1)
        self.pushButton_logoff = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_logoff.sizePolicy().hasHeightForWidth())
        self.pushButton_logoff.setSizePolicy(sizePolicy)
        self.pushButton_logoff.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton_logoff, 1, 0, 1, 2)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.pushButton_basket.setText(_translate("Widget", "Basket"))
        self.pushButton_buy.setText(_translate("Widget", "Buy Item"))
        self.pushButton_logoff.setText(_translate("Widget", "Log Off"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec())